---
- hosts: main
  vars:
    ansible_user: "{{ new_admin_user }}"
    ansible_port: "{{ new_ssh_port }}"
    ansible_become: yes
    ansible_become_pass: "{{ new_admin_pass }}"
  roles:
    # Install basic utils
    - role: utils
      tags:
        - utils
    # Install UFW firewall
    - role: ufw
      tags:
        - ufw
    # Install mail server
    - role: emailwiz
      tags:
        - mail
    # Install mail backup scripts
    - role: mail-backup
      tags:
        - backup
        - mail-backup
    # Install fail2ban for imap/smtp
    - role: fail2ban
      tags:
        - fail2ban
    # Install mailgun relay
    - role: mailgun-relay
      tags:
        - mailgun
    # Add knockd
    - role: knock
      tags:
        - knock
    # Install docker
    - role: docker
      tags:
        - docker
    # Install nginx
    - role: nginx
      tags:
        - nginx
    # Bring up nextcloud
    - role: nextcloud
      tags:
        - nextcloud
    # Nextcloud backup scripts
    - role: nextcloud-backup
      tags:
        - backup
        - nextcloud-backup
  post_tasks:
    - name: Get contents of dns_emailwizard
      tags:
        - main
      shell:
        cmd: cat /root/dns_emailwizard
      register: dns_emailwizard_content
    - name: Note these mail DNS records
      tags:
        - main
      debug:
        msg: "{{ dict(['record_name', 'record_type', 'value'] | zip(item.split('\t'))) }}"
      loop: "{{ dns_emailwizard_content.stdout.split('\n') }}"
