- name: Install utils
  apt:
    pkg:
      - curl
      - vim
      - git
      - htop
      - python3-pip
- name: Remove temp user
  user:
    name: "{{ temp_user }}"
    state: absent
    remove: yes
